Mirantis/mk-lab-salt-model

classes/system/salt/master/formula/git/stacklight.yml
=> Use the stacklight branch of collectd

classes/system/keystone/client/stacklight.yml, nodes/control/cfg01.mk20-stacklight-advanced.local.yml, nodes/control/cfg01.mk20-stacklight-basic.local.yml
Because Ceilometer isn't deployed in these environments.
=> Don't register Ceilometer for StackLight labs

classes/system/heka/log_collector/single.yml, classes/system/heka/metric_collector/single.yml, classes/system/nova/compute/cluster.yml, classes/system/nova/compute/single.yml
Otherwise service.nova.support isn't included.
=> Add service.nova.compute.kvm class to compute nodes

classes/cluster/mk20_stacklight_advanced/fuel/config.yml, classes/cluster/mk20_stacklight_basic/fuel/config.yml, classes/cluster/mk22_lab_advanced/fuel/config.yml, classes/system/elasticsearch/client/single.yml
Reverts Mirantis/mk-lab-salt-model#85
I will move the classification into reclass
=> Revert "Enable Elasticsearch client on mon01"

classes/cluster/mk22_lab_dvr/fuel/config.yml, classes/cluster/mk22_lab_dvr/init.yml, classes/cluster/mk22_lab_dvr/openstack/compute.yml, classes/cluster/mk22_lab_dvr/openstack/control.yml, classes/cluster/mk22_lab_dvr/openstack/gateway.yml, classes/cluster/mk22_lab_dvr/openstack/init.yml, classes/cluster/mk22_scale_mirantis/openstack/compute.yml, classes/system/linux/network/interface/ovs_lab_dvr.yml, classes/system/neutron/compute/cluster.yml, classes/system/neutron/control/openvswitch/cluster.yml, classes/system/neutron/gateway/cluster.yml, classes/system/nova/compute/cluster.yml, classes/system/opencontrail/compute/cluster.yml, classes/system/reclass/storage/system/openstack_gateway_single.yml
This setups provides full DVR VXLAN integration inside of heat template cloud.
It requires some network changes in underlay cloud to support overlay network
static routes.
=> Introduce mk22_lab_dvr configuration

classes/cluster/mk20_stacklight_advanced/stacklight/server.yml, classes/cluster/mk20_stacklight_basic/stacklight/server.yml, classes/cluster/mk22_full_scale/stacklight/monitor.yml, classes/cluster/mk22_lab_advanced/stacklight/init.yml, classes/cluster/mk22_lab_advanced/stacklight/server.yml, classes/cluster/mk22_scale_mirantis/stacklight/monitor.yml, classes/system/collectd/remote_client/cluster.yml, classes/system/collectd/remote_client/output/heka.yml, classes/system/collectd/remote_client/single.yml, classes/system/heka/aggregator/cluster.yml, classes/system/heka/remote_collector/cluster.yml, classes/system/keepalived/cluster/instance/stacklight_monitor_vip.yml, scripts/stacklight_infra_install.sh, scripts/stacklight_monitor_install.sh
This depends on https://github.com/tcpcloud/salt-formula-collectd/pull/22
=> Deploy remote collectd and collector on the monitoring node(s)

classes/cluster/mk20_stacklight_advanced/openstack/compute.yml, classes/cluster/mk20_stacklight_advanced/openstack/control.yml, classes/cluster/mk20_stacklight_basic/openstack/compute.yml, classes/cluster/mk20_stacklight_basic/openstack/control.yml, classes/system/heka/alarm/openstack_compute.yml, classes/system/heka/alarm/openstack_control.yml
This commits overrides CPU triggers defined in the Linux formula. This is to use specific rules on OpenStack control and compute nodes.
=> Add control nodes and compute nodes specific alarms

scripts/fuel_config_verify.sh, scripts/fuel_infra_install.sh, scripts/opencontrail_control_install.sh, scripts/openstack_compute_install.sh, scripts/openstack_control_install.sh, scripts/openstack_infra_install.sh, scripts/stacklight_infra_install.sh, scripts/stacklight_monitor_install.sh
This allows  to find out failed states afterwards
=> Log outputs of bootstrapping scripts

classes/system/nagios/server/init.yml
This is useless and totally wrong in cluster deployment
=> Remove Nagios UI check

classes/cluster/mk22_lab_advanced/stacklight/init.yml, scripts/openstack_infra_install.sh
it resolve No haproxy logs available
Closes-bug: PROD-8247
=> Rsyslog restart in install script for haproxy logs

scripts/stacklight_monitor_install.sh
This allow to be generic across all labs.
=> Find the StackLight VIP from pillar _param

classes/system/aodh/server/cluster.yml, classes/system/aodh/server/single.yml, classes/system/ceilometer/agent/cluster.yml, classes/system/ceilometer/agent/single.yml, classes/system/ceilometer/compute/cluster.yml, classes/system/ceilometer/server/cluster.yml, classes/system/ceilometer/server/single.yml, classes/system/galera/server/database/aodh.yml, classes/system/haproxy/proxy/listen/openstack/aodh.yml, classes/system/haproxy/proxy/listen/openstack/ceilometer.yml, classes/system/heka/ceilometer_collector/single.yml, classes/system/keystone/client/service/aodh.yml, classes/system/salt/master/formula/git/openstack.yml
Aodh and Ceilometer system classes were created in this commit.
Also keystone, galera and mysql classes were changed to support
aodh installation.
=> Change and create system classes for support Mitaka Ceilometer

classes/system/influxdb/server/single.yml
Depends on https://github.com/tcpcloud/salt-formula-influxdb/pull/16
=> Configure InfluxDB retention policy

classes/system/heka/remote_collector/cluster.yml, classes/system/heka/remote_collector/input/amqp.yml, classes/system/heka/remote_collector/single.yml
This patch removes the configuration that enables the collect of
notifcations to avoid conflict if ceilometer is enabled.
=> Don't configure the collect of notifications

classes/cluster/mk22_lab_advanced/fuel/config.yml
As two computes are used we need to use openstack_compute_multi
=> Use multi compute with mk22_lab_advanced

classes/cluster/mk22-qa-bare-metal-01/init.yml
Updated the MK22 QA bare-metal model (fixed IPs and some other issues with the initial version of the model for QA baremetal lab)
=> Updated the MK22 QA bare-metal model

scripts/openstack_compute_install.sh
=> Wait for compute nodes to answer salt pings after reboot

scripts/opencontrail_control_install.sh, scripts/openstack_compute_install.sh
=> Remove hardcoded hostnames and IP addresses

classes/system/nagios/server/init.yml
This PR depends on https://github.com/tcpcloud/salt-formula-nagios/pull/12/
=> Add environment name into Nagios email subjects

classes/cluster/mk22_qa_lab01/openstack/init.yml
It was decded for MK24 go with contrail 3.02
=> PROD-8613 Change contrail repo to oc30

classes/cluster/mk22_lab_dvr/openstack/compute.yml, classes/cluster/mk22_lab_dvr/openstack/control.yml, classes/cluster/mk22_lab_dvr/openstack/gateway.yml, classes/cluster/mk22_lab_dvr/openstack/init.yml
This is a similar change to what has been done for mk22_lab_basic and
mk22_lab_advanced.
=> Use openstack_control_address for mk22_lab_dvr
