Mirantis/mk-lab-salt-model

classes/system/nginx/server/proxy/openstack_web.yml
This commit fixes the nginx configuration for openstack-web (OpenStack Horizon).
This follows up on commit 9f01df8647df61e282a06528184c96d8c8e013a7 which changed the model to deploy Horizon on the controller nodes instead of the config node.
=> Fix nginx configuration for openstack-web

classes/system/rabbitmq/server/openstack.yml
This commit removes the `system/rabbitmq/server/openstack.yml` class file, which
is not used. The OpenStack-related RabbitMQ configuration is in
`system/openstack/control/mk20_lab.yml`.
=> Remove unused model file

classes/system/heka/metric_collector/single.yml, classes/system/openstack/common/mk20_stacklight.yml
This declares an InfluxDB output plugin in `heka:metric_collector:output`. This depends on https://github.com/tcpcloud/salt-formula-heka/pull/13, which should be merged first.
=> Add InfluxDB parameters

classes/system/salt/master/formula/git/openstack.yml, classes/system/salt/master/formula/git/saltstack.yml, nodes/control/cfg01.mk20-stacklight-basic.local.yml
Instead of overriding "revision" at the config node level this commit sets "revision" in the system.salt.master.formula.git.openstack/saltstack classes directly. This is to be consistent with what was done in 7251fc9, and to use the StackLight branches for both stacklight-basic and stacklight-advanced.
=> Use stacklight branches for both basic & advanced

classes/system/influxdb/server/single.yml
The new formula is using privilege instead of grant. And we enabled the
admin user.
=> Fix issue in InfluxDB model

classes/system/heka/log_collector/single.yml
Enable Heka for glance, heat, keystone and neutron now that the following are merged:
* https://review.openstack.org/#/c/391439/ (neutron)
* https://review.openstack.org/#/c/391433/ (glance)
* https://review.openstack.org/#/c/391436/ (heat)
* https://review.openstack.org/#/c/391470/ (keystone)
(We still don't collect Nova logs.)
=> Enable Heka for glance, heat, keystone and neutron

classes/system/stacklight/server/cluster.yml, classes/system/stacklight/server/single.yml
This commit sets `kibana_elasticsearch_host` to "mon" in the
`stacklight.server.single` class and to `"${_param:monitor_vip_address}"` in the
`stacklight.server.cluster` class.
=> Properly set kibana_elasticsearch_host

classes/system/elasticsearch/server/single.yml, classes/system/heka/log_collector/single.yml, classes/system/openstack/common/mk20_stacklight.yml
Configure the Elasticsearch output on the log_collector.
This depends on https://github.com/tcpcloud/salt-formula-heka/pull/18, which should be merged first.
=> Add Elasticsearch parameters

classes/system/heka/metric_collector/single.yml
Set the InfluxDB time precision in the user model, and use one parameter for setting the time precision in both the InfluxDB output and the InfluxDB accumulator filter.
This depends on https://github.com/tcpcloud/salt-formula-heka/pull/17, which should be merged first.
=> Add influxdb_time_precision parameter

classes/system/heka/remote_collector/single.yml, classes/system/stacklight/server/single.yml
Deploying the `remote_collector` doesn't currently work. We don't need the `remote_collector` for now, so this commit just removes the `system.heka.remote_collector.single` class.
This is the error we currently get when applying the "heka" state on the monitoring node:
```
----------
ID: /etc/remote_collector/output_metric_collector.toml
Function: file.managed
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
**cdata['kwargs'])
File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
return f(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1644, in managed
**kwargs
File …
```
=> Do not apply the remote_collector class

classes/system/heka/metric_collector/single.yml
With https://github.com/tcpcloud/salt-formula-heka/pull/19 the InfluxDB output configuration uses "influxdb_time_precision" set on "metric_collector".
=> Do not set time_precision on InfluxDB output

classes/system/openstack/common/mk20_stacklight.yml
Because it doesn't work well currently in different timezones.
=> Configure UTC timezone for StackLight labs

classes/system/heka/log_collector/single.yml
This commit prevents the `log_collector` from looking for Nova logs on non-nova nodes.
=> Remove nova section from log_collector.single class

classes/system/grafana/server/single.yml
This patch renames datasource because the name of the datasource is
currently hardcoded into dashboards for annotations.
=> Set grafana binding and rename datasource

classes/system/heka/aggregator/single.yml, classes/system/heka/metric_collector/single.yml, classes/system/openstack/common/mk20_stacklight.yml
This configures the heka aggregator on the monitoring node. This is a companion PR for https://github.com/tcpcloud/salt-formula-heka/pull/27, which needs to be merged first.
=> Configure the heka aggregator

classes/system/heka/aggregator/single.yml, classes/system/heka/log_collector/single.yml, classes/system/heka/metric_collector/single.yml, classes/system/heka/remote_collector/single.yml, classes/system/openstack/common/mk20_stacklight.yml
This adapts the user model to the Heka configuration mechanism implemented in https://github.com/tcpcloud/salt-formula-heka/pull/38.
=> Adapt model to new Heka config mechanism

classes/system/heka/remote_collector/single.yml
This enables the aggregator output in the remote collector. Requires https://github.com/tcpcloud/salt-formula-heka/pull/43.
=> Enable aggregator output in remote collector

classes/system/linux/system/trusty.yml
Because otherwise the ntp collectd plugin isn't configured.
=> Enable NTP mode7 queries for Trusty nodes too

classes/cluster/mk22_qa_lab01/fuel/config.yml, classes/cluster/mk22_qa_lab01/init.yml
We have 2 computes spawned, but use openstack_compute_single,
replace it with multi one
=> Add usage of multi computes

classes/system/grafana/server/single.yml, classes/system/openstack/compute/mk20.yml, classes/system/openstack/control/mk20.yml, classes/system/stacklight/server/cluster.yml, classes/system/stacklight/server/single.yml
This patch activates the remote dashboards and disables the local
dashboards. All dashboards that are currently provided by the Grafana
formula will probably be provided by each service.
=> Enable remote dashboards

classes/system/openstack/common/mk20_stacklight_basic.yml
The monitoring node get 'mon' as hostname when using 'host' grains while it
should be 'mon01'.
=> Fix /etc/host for the mon node

classes/system/openstack/common/mk20_stacklight.yml, classes/system/reclass/storage/system/mk20_stacklight_advanced.yml, classes/system/stacklight/server/cluster.yml
This patch removes the declaration of InfluxDB clustering and install
InfluxDB only on mon01. There is no clustering with the new InfluxDB
server.
=> Install InfluxDB on a single node

classes/system/openstack/common/mk20_stacklight_advanced.yml
This patch replaces the IP used in /etc/hosts by the correct value.
=> Fix an issue when configuring /etc/hosts

classes/system/elasticsearch/server/cluster.yml
This patch sets the number of replicas according to the number of
instances.
=> Update number of replicas for Elasticsearch

classes/system/kibana/server/single.yml, classes/system/monitoring/server/single.yml, classes/system/stacklight/server/cluster.yml, classes/system/stacklight/server/single.yml
This patch binds Kibana to single address instead of the default
0.0.0.0.
=> Bind Kibana to a specific IP

classes/cluster/mk20_stacklight_basic/init.yml, classes/cluster/mk20_stacklight_basic/stacklight/client.yml, classes/system/collectd/client/remote.yml
This is a PR for `Mirantis:dash`.
This fixes the `mk20_stacklight_basic.stacklight.client` class, and adds this class to the `mk20_stacklight_basic` class to deploy `collectd`, `log_collector` and `metric_collector` on all the nodes.
=> Deploy stacklight agents on all the nodes

scripts/fuel_infra_install.sh
This is a PR for `Mirantis:bash`.
This PR modifies the `fuel_infra_install.sh` script to sync the states and modules defined in formulas to the minions.
ISSUE: this turns out to not be sufficient, a restart of salt-minion is still required for the minion to actually find the synchronized states/modules.
=> Sync Salt states and modules

scripts/stacklight_infra_install.sh
This a PR for `Mirantis:dash`.
`saltutil.refresh_modules` makes salt-minion re-read the grains from /etc/salt/grains. That is a necessary step before pushing the grains to Salt Mine.
=> Refresh modules between mine.flush and update

classes/cluster/mk20_lab_basic/openstack/control.yml, classes/system/cinder/control/cluster.yml, classes/system/galera/server/cluster.yml, classes/system/glance/control/cluster.yml, classes/system/haproxy/proxy/listen/elasticsearch.yml, classes/system/haproxy/proxy/listen/kibana.yml, classes/system/haproxy/proxy/listen/rabbitmq.yml, classes/system/haproxy/proxy/listen/redis.yml, classes/system/heat/server/cluster.yml, classes/system/keystone/server/cluster.yml, classes/system/neutron/control/cluster.yml, classes/system/nova/control/cluster.yml, classes/system/opencontrail/control/analytics.yml, classes/system/opencontrail/control/cluster.yml, classes/system/opencontrail/control/control.yml, classes/system/opencontrail/control/single.yml
This changes the `haproxy:proxy:listen` configuration for StackLight. More specifically:
* set `service_name` for aggregations in StackLight (see https://github.com/tcpcloud/salt-formula-haproxy/pull/11)
* use more consistent listen names
=> Change haproxy:proxy:listen config for StackLight

classes/cluster/mk20_stacklight_advanced/stacklight/server.yml, classes/system/influxdb/server/cluster.yml, classes/system/reclass/storage/system/stacklight_server_cluster.yml
This patch fixes an error in the declaration of the repositorie. We also
use the single deployment instead of the cluster one because there is no
more cluster in the new InfluxDB version.
=> Fix InfluxDB repo and use single instead of cluster

classes/system/linux/system/single.yml, classes/system/ntp/client/single.yml
Because otherwise the ntp collectd plugin isn't configured.
=> Enable NTP mode7 queries by default

classes/cluster/mk20_stacklight_advanced/fuel/config.yml, classes/cluster/mk20_stacklight_basic/fuel/config.yml, classes/cluster/mk22_lab_advanced/fuel/config.yml, classes/system/salt/master/formula/git/openstack.yml, classes/system/salt/master/formula/git/saltstack.yml, classes/system/salt/master/formula/git/stacklight.yml
Although this change introduces some duplication in the definition of the labs, it is necessary if labs other than the StackLight ones want to be deployed using Git formulas.
=> Fix the use of the StackLight branches

classes/system/elasticsearch/client/single.yml, classes/system/reclass/storage/system/stacklight_server_cluster.yml, classes/system/reclass/storage/system/stacklight_server_single.yml
This patch classifies Elasticsearch client on mon01.
=> Enable Elasticsearch client for StackLight

classes/cluster/mk20_stacklight_basic/stacklight/server.yml, classes/system/influxdb/server/single.yml
- Set mounting tmpfs by default 
- For access to elasticsearch we should use the same address as bind address, not localhost
=> Add tmpfs for wal, fix elasticsearch address

classes/cluster/mk22_full_scale/stacklight/client.yml, classes/cluster/mk22_lab_advanced/stacklight/client.yml, classes/cluster/mk22_lab_advanced/stacklight/init.yml
BTW, the param `influxdb_stacklight_password` should be named differently IMHO.
This has been renamed by this commit e21bcd962a0dca82e259e19e896f06d9b4c74766
@cznewt  why not just name it `ìnfluxdb_password` ?
=> Fix the infinite recursion for stacklight.client

classes/cluster/mk20_stacklight_advanced/fuel/config.yml, classes/cluster/mk20_stacklight_basic/fuel/config.yml, classes/cluster/mk22_full_scale/fuel/config.yml, classes/cluster/mk22_scale_mirantis/fuel/config.yml, classes/system/salt/master/git.yml
Otherwise all labs have to define 'salt_master_environment_repository'
and 'salt_master_environment_revision' even though they don't use the
Git formulas.
=> Include default branch and repo for Git formulas

classes/cluster/mk20_lab_advanced/openstack/init.yml, classes/cluster/mk20_stacklight_advanced/openstack/control.yml, classes/cluster/mk20_stacklight_advanced/openstack/init.yml, classes/cluster/mk20_stacklight_basic/openstack/control.yml, classes/cluster/mk20_stacklight_basic/openstack/init.yml, classes/cluster/mk22_lab_advanced/openstack/control.yml, classes/system/galera/server/database/grafana.yml, classes/system/grafana/server/single.yml
This patch configures Grafana to use MySQL installed by OpenStack
instead of SQlite3. It configures the MySQL database with a new table
and a new user for Grafana and it configures Grafana to use the MySQL.
=> Use MySQL/Galera for Grafana

classes/system/glance/control/cluster.yml
Checks are currently disabled for glance_registry_api in the HAProxy configuration. This enables them.
=> Enable checks for haproxy glance_registry_api

classes/system/nova/compute/cluster.yml, classes/system/nova/compute/single.yml
MK22 [nova]: Nova instance migration fails because of missing ssh
key
Introduce new param variables nova_compute_ssh_public and
nova_compute_ssh_private
Closes-bug: PROD-8216
=> Add default ssh key for nova user on compute

classes/cluster/mk20_stacklight_advanced/stacklight/proxy.yml, classes/cluster/mk20_stacklight_basic/stacklight/proxy.yml, classes/system/nginx/server/proxy/nagios_web.yml
The port 8001 is used internaly by collectors/aggregator to push statuses.
=> Fix Nginx proxy for Nagios UI port

scripts/bootstrap_all.sh, scripts/stacklight_infra_install.sh, scripts/stacklight_monitor_install.sh
This commit changes the StackLight deploy scripts, stacklight_infra_install.sh and stacklight_monitor_install.sh.
stacklight_infra_install.sh now just takes care of the backends/infrastructure, installing Elasticsearch, Kibana, InfluxDB and Grafana on the monitoring nodes.
stacklight_monitor_install.sh finalizes the installation of StackLight, deploying the Collectd and Heka agents and configuring them based on the metadata in Salt Mine.
The stacklight_monitor_install.sh can be run at will. In particular the script can be run after changing the monitoring configuration. It will take care of updating the metadata in Salt Mine and re-configuring the
StackLight agents as appropriate.
=> Rework the StackLight deploy scripts

classes/cluster/mk22_lab_advanced/stacklight/server.yml
InfluxDB is deployed only on the mon01 node.
=> Fix InfluxDB deployment for mk22_lab_advanced

classes/system/collectd/client/output/heka.yml, classes/system/collectd/remote_client/output/heka.yml
Currently the `collectd` process logs both to `/var/log/collectd.log` file (through the `logfile` plugin) and to Syslog. This patch disables the logging to Syslog.
=> Disable collectd syslog logging

classes/system/nagios/server/init.yml
Nagios uses Syslog but passive_checks and external_commands
are really too chatting since StackLight is intensively using them.
=> Make Nagios less chatty

classes/system/nagios/server/init.yml
Since LDAP authentication is supported, it makes sense to have a common
key 'host'.
=> Rework metadata hierarchy for authentication parameters

classes/system/ceilometer/server/cluster.yml, classes/system/ceilometer/server/single.yml, classes/system/galera/server/database/aodh.yml, classes/system/heka/ceilometer_collector/single.yml
Ceilometer and Aodh classes use couple of non actual config names. This CR fix it.
=> Change names of couple ceilometer related configs to actual in sysclasses 

classes/system/heka/alarm/openstack_compute.yml, classes/system/heka/alarm/openstack_control.yml
We will remove the `majority_of_members` policy in the (near) future. This change suggests using `status_of_members` for the `control_nodes` and `compute_nodes` alarm clusters.
=> Use policy status_of_members for node clusters

classes/system/heka/ceilometer_collector/single.yml
This patch needs to be merged when https://github.com/tcpcloud/salt-formula-heka/pull/92 is merged.
=> Use the amqp_ prefix for AMQP variables

classes/cluster/mk22_lab_basic/openstack/control.yml, classes/system/linux/system/repo/mos9.yml
Python-influxdb is needed for Ceilometer in Mitaka. Because
this package provided by nightly xenial repository we add
and pin this repository with lower priority.
=> Add 9.0-latest repository for python-influxdb installation

classes/cluster/mk20_lab_advanced/fuel/config.yml, classes/cluster/mk20_lab_advanced/openstack/compute.yml
Ceilometer out from compute node(s).
Changed to two computes.
=> Fixed mk20_lab_advanced

classes/cluster/mk22_lab_advanced/stacklight/init.yml, classes/system/heka/aggregator/cluster.yml, classes/system/heka/aggregator/single.yml, classes/system/heka/ceilometer_collector/single.yml, classes/system/heka/log_collector/single.yml, classes/system/heka/metric_collector/single.yml, classes/system/heka/remote_collector/cluster.yml, classes/system/heka/remote_collector/single.yml, classes/system/heka/server.yml, classes/system/nagios/server/init.yml
This allows Nagios to support several environments.
This is used by both:
https://github.com/tcpcloud/salt-formula-nagios/pull/11
https://github.com/tcpcloud/salt-formula-heka/pull/106
=> Add stacklight_environment parameter

classes/system/aodh/server/cluster.yml, classes/system/ceilometer/server/cluster.yml
Currently classes for Aodh and Ceilometer haproxies are referenced
from model. In this commit referencing is moved to sysclasses
for cluster deployment
=> Add Ceilometer and Aodh haproxy importing to sysclasses

classes/cluster/mk22_full_scale/stacklight/log.yml, classes/cluster/mk22_scale_mirantis/stacklight/log.yml, classes/system/elasticsearch/server/cluster.yml, classes/system/elasticsearch/server/storage/glusterfs.yml
This change separates the installation of GlusterFS for Elasticsearch
snapshots from the Elasticsearch system class for better flexibility.
It also removes the use of GlusterFS for the mk20 and mk22 StackLight
labs because it generates random errors during the deployment.
=> Split GlusterFS install from the Elastic class

classes/cluster/mk20_stacklight_advanced/init.yml, classes/cluster/mk20_stacklight_basic/init.yml, classes/cluster/mk22_full_scale/init.yml, classes/cluster/mk22_lab_advanced/init.yml, classes/cluster/mk22_lab_basic/init.yml, classes/system/rsyslog/client/single.yml, classes/system/salt/master/formula/git/stacklight.yml, scripts/fuel_infra_install.sh
With this change the `rsyslog` state is applied on all the nodes of the cluster. This change requires https://github.com/tcpcloud/salt-formula-rsyslog/pull/1.
=> Use the rsyslog formula and state

classes/cluster/mk20_stacklight_advanced/stacklight/init.yml, classes/cluster/mk20_stacklight_basic/stacklight/init.yml, classes/cluster/mk22_full_scale/stacklight/init.yml, classes/cluster/mk22_lab_basic/stacklight/init.yml, classes/cluster/mk22_scale_mirantis/stacklight/init.yml, classes/system/heka/server.yml, classes/system/nagios/server/init.yml
The previous version generated inconsistent labels between the
monitoring nodes and the other nodes. This change makes
stacklight_environment a mandatory parameter to avoid this problem.
=> Fix inconsistent Stacklight environment label

scripts/common_functions.sh, scripts/fuel_config_verify.sh
This prevents errors when lauching deployment scritps
too early (aka when all nodes are not yet bootstrapped
and answering to salt pings)
=> Add safety loop

classes/cluster/mk22_lab_advanced/fuel/config.yml, classes/cluster/mk22_lab_advanced/openstack/compute.yml, classes/cluster/mk22_lab_advanced/openstack/control.yml, classes/cluster/mk22_lab_advanced/openstack/init.yml, classes/cluster/mk22_lab_advanced/stacklight/server.yml, classes/cluster/mk22_lab_basic/fuel/config.yml, classes/cluster/mk22_lab_basic/openstack/compute.yml, classes/cluster/mk22_lab_basic/openstack/control.yml, classes/cluster/mk22_lab_basic/openstack/init.yml, classes/cluster/mk22_lab_basic/stacklight/server.yml, classes/system/ceilometer/server/cluster.yml, classes/system/ceilometer/server/single.yml, classes/system/heka/ceilometer_collector/single.yml, classes/system/influxdb/database/ceilometer.yml, classes/system/linux/system/repo/mos9_latest.yml, scripts/openstack_control_install.sh
This PR contains a changes which add right configs and classes for allowing Ceilometer, Aodh and ceilometer-collector into mk22_lab_basic and mk22_lab_advanced models.
Also, it contains one configs fix for Ceilometer and adding deployment mentioned applications to scripts
=> Add Openstack Telemetry to mk22_lab_basic and mk22_lab_advanced

scripts/common_functions.sh
This patch modifies the way we check that the number of compute nodes is
greater than 0. It fixes an issue that occurs when extglob is disabled
and doesn't support the extending pattern matching.
=> Modify the test of the number of compute nodes

scripts/stacklight_monitor_install.sh
This change makes sure that remote_collector, remote_collectd,
aggregator and nagios services are restarted when the corresponding
states are reapplied.
=> Restart StackLight services associated to the VIP

classes/cluster/mk22_lab_dvr/openstack/compute.yml, classes/cluster/mk22_lab_dvr/openstack/gateway.yml, classes/cluster/mk22_lab_ovs/openstack/compute.yml, classes/cluster/mk22_lab_ovs/openstack/gateway.yml
This patch replaces the old declaration of the Linux network interface
since it has been renamed into single_ovs_dvr.
=> Replace ovs_lab_dvr by single_ovs_dvr

classes/cluster/mk22_lab_advanced/init.yml, classes/cluster/mk22_lab_advanced/openstack/control.yml, classes/cluster/mk22_lab_basic/init.yml, classes/cluster/mk22_lab_basic/openstack/control.yml
Currently MongoDb class will be used by default during installation,
this code change it to InfluxDB and ElasticSearch
=> Add usage of InfluxDB backend for the Telemetry

classes/cluster/mk22_lab_advanced/openstack/control.yml, classes/cluster/mk22_lab_basic/openstack/control.yml
It is now required to use neutron.control.opencontrail.cluster class
when using OpenContrail instead of neutron.control.cluster.
=> Fix class for the Neutron control clusters

classes/cluster/mk22_lab_advanced/init.yml, classes/cluster/mk22_lab_basic/init.yml
Reclass model needs configs for ElasticSearch backend with
different names. Right names are defined in this commit
=> Add configs for ElasticSearch Telemetry backend into models

classes/cluster/mk22_lab_advanced/fuel/config.yml, classes/cluster/mk22_lab_advanced/openstack/proxy.yml, classes/cluster/mk22_lab_advanced/stacklight/proxy.yml, classes/cluster/mk22_lab_basic/fuel/config.yml, classes/cluster/mk22_lab_basic/openstack/proxy.yml, classes/cluster/mk22_lab_basic/stacklight/proxy.yml, classes/cluster/mk22_lab_dvr/fuel/config.yml, classes/cluster/mk22_lab_dvr/openstack/proxy.yml, classes/cluster/mk22_lab_dvr/stacklight/proxy.yml
This change is only for mk22_lab_basic, mk22_lab_dvr and
mk22_lab_advanced. Previously the proxy service was deployed on the
Salt master node but it didn't match with real-world deployments that
use dedicated proxy nodes.
=> Move the Nginx proxy service to prx01 node
